---
title       : Annotation Enrichment Analysis - An Alternative Method for 
              Evaluating the Functional Properties of Gene Sets
subtitle    : Kimberly Glass, Michelle Girvan
author      : Keith Hughitt
framework   : io2012
highlighter : highlight.js
hitheme     : tomorrow
widgets     : [mathjax]
mode        : selfcontained
github      : 
  user: khughitt
  repo: slidify-annotation_enrichment_analysis
--- .segue .dark

<!-- Custom Styles -->
<style type='text/css'>
    slides > slide {
        height: 800px;
        margin-top: -400px;
    }
    img {
        max-height: 560px;
        max-width: 964px;
    }
    slide a {border-bottom: none;}
    .small li { font-size: 20px; }
    .smaller li p { font-size: 16px; }
    .caption { font-size: 14px; display: block; }
    .references li { font-size: 14px; }
    .references li p { font-size: 14px; }
</style>

<!-- Custom JavaScript -->
<script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.7.min.js"></script>
<script type='text/javascript'>
$(function() {
    $("p:has(img)").addClass('centered');
});
</script>

## Background

---

## Background






---.references

## References

```{r refs, include=FALSE}
library(knitcitations)
cleanbib()
citep('10.1093/nar/gkn923')
```

```{r refs_output, echo=FALSE, results='asis'}
bibliography('html')
```
